#! /usr/bin/env bash

pkg='libgpg-error'
version='1.42'
url="https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-${version}.tar.bz2"
sha256='fc07e70f6c615f8c4f590a8e37a9b8dd2e2ca1e9408f8e60459c67452b925e23'
require=()
configure_extra=(--disable-shared --enable-static)
