#! /usr/bin/env bash

pkg='libksba'
version='1.6.2'
url="https://gnupg.org/ftp/gcrypt/libksba/libksba-${version}.tar.bz2"
sha256='fce01ccac59812bddadffacff017dac2e4762bdb6ebc6ffe06f6ed4f6192c971'
require=(libgpg-error)
configure_extra=(--disable-shared --enable-static)
