#! /usr/bin/env bash

pkg='libressl'
version='3.6.1'
url="https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-${version}.tar.gz"
sha256='acfac61316e93b919c28d62d53037ca734de85c46b4d703f19fd8395cf006774'
require=()
configure_extra=(--disable-shared --enable-static)
