#! /usr/bin/env bash

pkg='libgcrypt'
version='1.10.1'
url="https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-${version}.tar.bz2"
sha256='ef14ae546b0084cd84259f61a55e07a38c3b53afc0f546bffcef2f01baffe9de'
require=(libgpg-error)
configure_extra=(--disable-asm --disable-shared --enable-static)
