#! /usr/bin/env bash

pkg='libassuan'
version='2.5.5'
url="https://gnupg.org/ftp/gcrypt/libassuan/libassuan-${version}.tar.bz2"
sha256='8e8c2fcc982f9ca67dcbb1d95e2dc746b1739a4668bc20b3a3c5be632edb34e4'
require=(libgpg-error)
configure_extra=(--disable-shared --enable-static)
